name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  # Lint javascript files in the src/ folder
  lint-javascript:
    name: Lint JavaScript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install Standard Style
        run: npm install standard --global
      - name: Run Standard Style linter
        run: |
          cd src
          standard

  # Lint HTML and CSS files (ignores docs/ folder)
  lint-html-css:
    name: Lint HTML & CSS
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint HTML and CSS
        uses: super-linter/super-linter/slim@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          # Don't lint docs/ folder
          # See https://github.com/marketplace/actions/super-linter#how-to-use
          FILTER_REGEX_EXCLUDE: .*docs/.*
  
  # Create documentation website in docs/ folder from JSDocs comments
  create-documentation:
    name: Create JSDocs
    needs: lint-javascript
    runs-on: ubuntu-latest

    permissions:
      # Lets this job push the docs to the repository
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Write Documentation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          recurse: true
          # See different templates here: https://cancerberosgx.github.io/jsdoc-templates-demo/demo/
          template: clean-jsdoc-theme
          front_page: README.md
          output_dir: ./docs
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs
          git commit -a -m "Updated Documentation"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}